#!/usr/bin/env python
import os
import sys

# Constants
BASE_NAME = "template"
OUT_PATH = "../bin/"

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["target"] == "template_debug" or env["target"] == "editor":
    libname = "{}{}".format(BASE_NAME, ".d")
else:
    libname = BASE_NAME

if env["platform"] == "macos":
    target = "{}lib{}.dylib".format(OUT_PATH, libname)
else:
    target = "{}{}{}{}".format(OUT_PATH, env["SHLIBPREFIX"], libname, env["SHLIBSUFFIX"])

library = env.SharedLibrary(target, source=sources)

Default(library)
