#!/usr/bin/env python
import os
import sys

LIBNAME = "template"
OUTPATH = "../bin/"

env = SConscript("godot-cpp/SConstruct")

# print(env.Dump())

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

library = env.SharedLibrary(
    "{}{}{}{}".format(OUTPATH, env["SHLIBPREFIX"], LIBNAME, env["SHLIBSUFFIX"]),
    source=sources,
)

Default(library)
